"use client";

import Link from 'next/link';
import { ArrowLeft, Shield, FileText, UserCheck, AlertCircle } from 'lucide-react';

export default function TermsPage() {
    return (
        <div className="w-full max-w-4xl mx-auto flex flex-col items-center pt-8 animate-fade-in">
            <div className="w-full mb-8">
                <Link href="/" className="inline-flex items-center gap-2 text-slate-400 hover:text-white transition-colors group">
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>
            </div>

            <div className="glass-panel w-full rounded-3xl p-8 md:p-12 relative overflow-hidden border border-blue-500/10 shadow-xl">
                <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl" />

                <div className="mb-10 text-center">
                    <div className="inline-flex items-center justify-center p-4 bg-blue-500/10 rounded-full mb-6">
                        <FileText className="w-8 h-8 text-blue-400" />
                    </div>
                    <h1 className="text-3xl md:text-4xl font-bold mb-4 text-white">Terms of Service</h1>
                    <p className="text-slate-400">Last updated: March 2, 2026</p>
                </div>

                <div className="space-y-8 text-slate-300 leading-relaxed">

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold flex items-center gap-3 text-white border-b border-slate-800 pb-2">
                            <Shield className="w-5 h-5 text-blue-400" />
                            1. Acceptance of Terms
                        </h2>
                        <p>
                            By accessing and using the GitHub Portfolio Analyzer ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold flex items-center gap-3 text-white border-b border-slate-800 pb-2">
                            <UserCheck className="w-5 h-5 text-emerald-400" />
                            2. Use of Service
                        </h2>
                        <p>
                            Our Service analyzes public GitHub profiles and repositories to provide feedback, scoring, and actionable roadmaps. You agree to use this Service only for lawful purposes and in accordance with these Terms.
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-slate-400">
                            <li>You must not use the Service in any way that violates applicable local, national, or international law.</li>
                            <li>You may not attempt to reverse engineer, decompile, or bypass any security features of the Service.</li>
                            <li>You acknowledge that we rely on the GitHub API, and your usage must also comply with GitHub's current Terms of Service.</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold flex items-center gap-3 text-white border-b border-slate-800 pb-2">
                            <AlertCircle className="w-5 h-5 text-yellow-400" />
                            3. Limitation of Liability
                        </h2>
                        <p>
                            The feedback, scores, and roadmaps provided by our Service are generated by automated systems (including AI) and are intended for informational purposes only. We do not guarantee that following our suggestions will result in employment or interview offers.
                        </p>
                        <p>
                            Under no circumstances shall GitHub Portfolio Analyzer, its creators, or its affiliates be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the Service.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold flex items-center gap-3 text-white border-b border-slate-800 pb-2">
                            <FileText className="w-5 h-5 text-purple-400" />
                            4. Modifications to the Service
                        </h2>
                        <p>
                            We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time. We shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Service.
                        </p>
                    </section>

                </div>

                <div className="mt-12 pt-8 border-t border-slate-800 text-center text-sm text-slate-500">
                    If you have any questions about these Terms, please contact us at support@portfolioanalyzer.app.
                </div>
            </div>
        </div>
    );
}
